spring.application.name=hospital-management-system

server.port=9000

##spring.datasource.url=jdbc:h2:tcp://localhost/~/Desktop/data/data
##spring.datasource.url=jdbc:h2:tcp://192.168.29.96:9092/~/Desktop/data/data
spring.datasource.url=jdbc:h2:tcp://localhost/~/Desktop/data/data
spring.datasource.driverClassName=org.h2.Driver
# Username & Password will be injected from environment variables:
# SPRING_DATASOURCE_USERNAME
# SPRING_DATASOURCE_PASSWORD
spring.datasource.username=sa
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.jpa.open-in-view=false

server.servlet.context-path=/hospital

##jwt.secret=ThisIsASecretKeyThatIsLongEnoughToBeSecureForHS512Algorithm
#jwt.expiration.ms=86400000



